<?php

namespace App\Repositories\Contracts;

use App\Models\AI\Prediction;
use App\Models\User;
use Illuminate\Database\Eloquent\Collection;

/**
 * Interface for Prediction data access.
 */
interface PredictionRepositoryInterface
{
    /**
     * Retrieve a prediction by its ID.
     *
     * @param int $id
     * @return Prediction|null
     */
    public function findById(int $id): ?Prediction;

    /**
     * Create a new prediction record.
     *
     * @param array $data
     * @return Prediction
     */
    public function create(array $data): Prediction;

    /**
     * Find all predictions made by a specific user.
     *
     * @param User $user
     * @param int $perPage
     * @return \Illuminate\Contracts\Pagination\LengthAwarePaginator
     */
    public function findByUser(User $user, int $perPage = 15);

    /**
     * Find all predictions generated by a specific model.
     *
     * @param int $modelId
     * @return Collection
     */
    public function findByModel(int $modelId): Collection;
}